baseURL = "https://www.firmament.ca/"
languageCode = "en-us"
title = "Firmament-TCG"
theme = "hugo-book"

# Hugo-book specific configuration
[params]
  BookSearch = true
  BookComments = false
  BookToC = true
  BookSection = "posts"
  # BookLogo = "logo.png"

# Add menu items for navigation
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2